services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=localhost
      - SERVER_GO_ENV=${GO_ENV}
    container_name: go
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
